insert into product (id, name, price, created_at) values (1, 'Producto 1', 51234, now());
insert into product (id, name, price, created_at) values (2, 'Producto 2', 45123, now());
insert into product (id, name, price, created_at) values (3, 'Producto 3', 34512, now());
insert into product (id, name, price, created_at) values (4, 'Producto 4', 23451, now());
insert into product (id, name, price, created_at) values (5, 'Producto 5', 12345, now());
insert into product (id, name, price, created_at) values (6, 'Producto 6', 21345, now());
insert into product (id, name, price, created_at) values (7, 'Producto 7', 32145, now());
insert into product (id, name, price, created_at) values (8, 'Producto 8', 43215, now());
insert into product (id, name, price, created_at) values (9, 'Producto 9', 54321, now());
