spring:
  application:
    name: ms-oauth
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
     sampler:
       probability: 1.0
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    datasource:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
        path: /h2
    main:
      allow-bean-definition-overriding: true
server:
  servlet:
    contextPath: /
  port: ${PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      devx:
        oauth:
          clients: DEBUG