spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://localhost:9411/
    enabled: false
  sleuth:
     sampler:
       probability: 1.0
     enabled: false
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
zuul:
  routes:
    product:
      service-id: ms-product
      path: /api/products/**
    item:
      service-id: ms-item
      path: /api/items/**
    user:
      service-id: ms-user
      path: /api/users/**
    oauth:
      service-id: ms-oauth
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ConnectionTimeout: 3000
  ReadTimeout: 10000

config:
  security:
    oauth:
      client:
        id: frontapp
        secret: 12345
      jwt:
        key: secret_code