server:
  servlet:
    contextPath: /
  port: 9001
spring:
  application:
    name: ms-item
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
# configuracion ribbon
#ms-product:
#  ribbon:
#    listOfServers: "localhost:9000, localhost:8999"
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ConnectionTimeout: 3000
  ReadTimeout: 10000

logging:
  level:
    com:
      devx:
        item:
          msitem:
            restclient:
              clients: DEBUG

